### ISSUE TITLE
Sharing volume for data

### ISSUE THREAD

**Issue by saurabhmathur** [vsouza/docker-dynamoDB-local#2]
Hey,

I am trying map the data volume from the docker to my local drive to preserve the data in my environment across set up and tear down processes.

I am running this on a mac running macOS Sierra 10.12.1 and I have a folder ( /Users/Shared/dynamodb ), on my computer's hard drive, defined with drwxrwxrwx permissions.

Following your documentation, when I run the docker command as follows I see the docker coming up fine and I am able to create new tables and store data:
`docker run -d -p 8000:8000 --expose 8000 --name dynamodb vsouza/dynamo-local --port 8000 --path ./mydb`

But in order to map volumes, when I run the following command, I see errors in docker logs:
`docker run -d -p 8000:8000 --expose 8000 -v /Users/Shared/dynamodb:/mydb --name dynamodb vsouza/dynamo-local --port 8000 --path ./mydb`

Following is the error trace in docker:

`Listening at http://0.0.0.0:8000`

`events.js:72  throw er; // Unhandled 'error' event`

`OpenError: IO error: ./mydb: Invalid argument`
`         at /usr/lib/node_modules/dynalite/node_modules/levelup/lib/levelup.js:119:34`
`         at /usr/lib/node_modules/dynalite/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16`

Do I need to do something special to map the data volume in this case?

**Comment by vsouza** [comment]
I cannot reproduce this error here.

When I executed your command: 
`docker run -d -p 8000:8000 --expose 8000 -v /Users/Shared/dynamodb:/mydb --name dynamodb vsouza/dynamo-local --port 8000 --path ./mydb`

I got success.

```
total 24
drwxr-xr-x  7 vinicius.souza  wheel   238B Nov 29 12:16 .
drwxrwxrwt  6 root            wheel   204B Nov 29 12:16 ..
-rw-r--r--  1 vinicius.souza  wheel     0B Nov 29 12:16 000003.log
-rw-r--r--  1 vinicius.souza  wheel    16B Nov 29 12:16 CURRENT
-rw-r--r--  1 vinicius.souza  wheel     0B Nov 29 12:16 LOCK
-rw-r--r--  1 vinicius.souza  wheel    57B Nov 29 12:16 LOG
-rw-r--r--  1 vinicius.souza  wheel    50B Nov 29 12:16 MANIFEST-000002
```

detail, I didn't created the folder (/Users/Shared/dynamodb) before run this command, let the Docker create folder for you.
